namespace: modules\config\tests
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Yii2:
            cleanup: false
            configFile: 'tests/_config/test.php'
coverage:
    enabled: true
    whitelist:
            include:
                - models/*
                - params/*
                - components/DConfig.php
            exclude:
                - messages/*
                - views/*
